name: GitOps

on:
  push:
    branches:
      - 'env-*'

jobs:
  manage-infrastructure:
    runs-on: ubuntu-22.04
    environment: prod
    outputs:
      application_name: ${{ steps.infrastructure-deployment.outputs.application_name }}
      application_url: ${{ steps.infrastructure-deployment.outputs.application_url }}
      resource_group: ${{ steps.infrastructure-deployment.outputs.resource_group }}
    steps:
      - name: Apply Terraform configuration
        id: infrastructure-deployment
        uses: microsoft/nubesgen-actions/gitops-apply-terraform@v0.13.0
        env:
          TF_VAR_application_name: ${{ vars.TF_VAR_APPLICATION_NAME }}
          TF_VAR_custom_domain_name: ${{ vars.TF_VAR_CUSTOM_DOMAIN_NAME }}
          TF_VAR_container_certificate: ${{ secrets.TF_VAR_CONTAINER_CERTIFICATE }}
          TF_VAR_container_certificate_password: ${{ secrets.TF_VAR_CONTAINER_CERTIFICATE_PASSWORD }}
          TF_VAR_docker_hub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          TF_VAR_docker_hub_password: ${{ secrets.DOCKERHUB_TOKEN }}
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          tf_storage_account: ${{ secrets.TF_STORAGE_ACCOUNT }}
